image : composer

stages:
  - build
  - test

before_script:
  - apk update
  - apk add --no-cache sqlite php7-pdo_sqlite

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - htdocs/vendor
    - htdocs/bin/

install_dependencies:
  stage: build
  artifacts:
    paths:
      - htdocs/vendor
  script:
    - cd htdocs
    - composer install
    - php bin/console doctrine:database:create --if-not-exists --env=test
    - php bin/console doctrine:schema:update --force --env=test
    - php bin/console doctrine:fixtures:load --env=test

test_phpunit:
  stage: test
  script:
    - cd htdocs
    - php bin/phpunit