image : composer

stages:
  - build
  - test

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - htdocs/vendor
    - htdocs/bin/

install_dependencies:
  stage: build
  artifacts:
    paths:
      - htdocs/vendor
  script:
    - pwd
    - cd htdocs
    #- chmod 777 ./composer_ci
    #- ./composer_ci install
    - composer install

test_phpunit:
  stage: test
  script:
    - pwd
    - cd htdocs
    - php bin/phpunit