version: '3'

services:
    # Lance un serveur web apache
    web:
        build: docker/apache2
        ports:
            - 8080:80
            - 444:443
        expose:
            - 80
            - 443
        volumes:
            - ./htdocs:/usr/local/apache2/htdocs
        depends_on:
            - db
        environment:
          APPLICATION_ENV: development
          DEVELOPMENT_MODE: "false"
          WEB_HTTP: "true"

    # Lance un serveur PHP FPM qui sera lié à appache
    php:
        build: docker/php
        # Récupère les volumes définis sur web
        volumes:
            - ./htdocs:/usr/local/apache2/htdocs
        # Lance un serveur MySQL
        tty: true
        links:
            - db:db
    db:
        image: mysql:5.7
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        # Mapping de port pour se connecter à la db depuis l'extérieur du container
        ports:
            - 3306:3306

    # phpmyadmin
    pma:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8081:80
        links:
            - db:db

    # composer
    composer:
        build: docker/composer
        restart: 'no'
        volumes:
            - ./htdocs:/app
        tty: true
        links:
            - db:db