api_platform:
    resource: .
    type: api_platform
    prefix: /api

api_login_check:
    path: /api/login

api_enable_account_request:
    path: /api/customers/enable-account/{email}/{token}
    methods: ['GET']
    controller: App\Controller\Customer\EnableAccount

#api_customers_reset_password_item:
    #path: /api/customers/{id}/reset-password/{email}/{token}
    #methods: ['GET', 'PATCH']
    #controller: App\Controller\Customer\ResetPassword