#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
    path: /api/login

confirm_register:
    path: /api/confirm/{token}/{email}
    controller: App\Controller\RegisterController::confirmRegister

reset_password:
    path: /api/reset-password/{email}
    controller: App\Controller\ForgotPasswordController::resetPassword

check_password:
    path: /api/forgot-password/{token}
    controller: App\Controller\ForgotPasswordController::checkToken

update_password:
    path: /api/forgot-password/{token}/{password}
    controller: App\Controller\ForgotPasswordController::updatePassword
    methods: POST